### ISSUE TITLE
Cannot load the CDN resources

### ISSUE THREAD

**Issue by YanmaY** [exceptionless/Exceptionless.UI#195]
I am from China. I have deployed ES (6.0.0) project through Docker, but I cannot load the CDN resources of the project. 
(In version 4.0, I can modify the reference address in index.html.)
Please lend me a hand.

**Comment by niemyjski** [comment]
Hello, There is currently no way to do this unless you did `docker exec` into the container and your changes would be lost on a container restart. We would be willing to accept a pr to move all cdn scripts into a vendor bundle.

**Comment by YanmaY** [comment]
Yes! There are mainly these scripts: 
- bootstrap.min.css
- font-awesome.min.css
- jquery.min.js
- lodash.min.js
- bootstrap.min.js.
And thank you for answering my question.
![cdn](https://user-images.githubusercontent.com/7043862/88121943-cf186880-cbf9-11ea-9d53-b18430b3ffe1.png)

**Comment by niemyjski** [comment]
Is there a CDN that works for you that we could possibly switch out to easier?

**Comment by YanmaY** [comment]
Sorry to reply you so late.The [jsDelivr](https://www.jsdelivr.com/)  is available to me:
https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css
https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js
https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css
https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js
https://cdn.jsdelivr.net/npm/lodash@4.17.15/lodash.min.js

**Comment by niemyjski** [comment]
We’d be willing to accept a pr to change our cdn host to this Or to embed the libraries, it seems like others are using it and it’s safe.

**Comment by YanmaY** [comment]
I have submitted a pr and signed the CLA already. And thank u again :)
#197

**Comment by niemyjski** [comment]
I've merged this in, can you please verify that this is working as expected with the latest nightly docker image produced from: https://github.com/exceptionless/Exceptionless.UI/runs/918804255?check_suite_focus=true

**Comment by YanmaY** [comment]
I'd like to do but I don't know how to do 😂，I'm not very good at Docker yet🤣

**Comment by XLJ-CN** [comment]
sorry sir  ，I read this page in detail
I try to change the index.html page in docker,then i get a security error 
![图片](https://user-images.githubusercontent.com/30283517/88767592-75d9a780-d1ac-11ea-92b3-707bed34dc60.png)
I think it should change the source code here right ?
![图片](https://user-images.githubusercontent.com/30283517/88767670-8f7aef00-d1ac-11ea-99fe-11962ba1fdc4.png)
and how to do now   ,thank you very much

**Comment by niemyjski** [comment]
My apologies for the late reply. Would someone mind submitting a pr to update this server side. We just need to change the hosts that were added/removed from the front end. https://github.com/exceptionless/Exceptionless/blob/master/src/Exceptionless.Web/Startup.cs#L160-L188

**Comment by XLJ-CN** [comment]
sorry I'm not good at git yet。Wating for your  new version，waiting for your release。 and thank you very much

**Comment by niemyjski** [comment]
We have a nightly ci feed that is going out with updated docker images but we'll try and get a release pushed today for this. I just updated the server side to allow these changes. Thanks for all of your help.

**Comment by niemyjski** [comment]
https://github.com/exceptionless/Exceptionless.UI/releases/tag/v2.9.1 UI is pushed server release will be following.

**Comment by niemyjski** [comment]
I just pushed https://github.com/exceptionless/Exceptionless/releases/tag/v6.1.1 please update your self hosted instances with the latest images when they are out.

**Comment by YanmaY** [comment]
@niemyjski I tried the new version but...
![image](https://user-images.githubusercontent.com/7043862/90097171-e87b8300-dd67-11ea-8aad-efe0e7a4fdd0.png)

**Comment by XLJ-CN** [comment]
sorry sir ,it still get many errors about css,js,font
![图片](https://user-images.githubusercontent.com/30283517/90104013-1667c400-dd76-11ea-9945-76e1db2c7f17.png)
I'm very moved by your new version，and i will wait for   repair it

**Comment by niemyjski** [comment]
@XLJ-CN You are getting that because you also need to update the backend that allows the policy. Can you please confirm your server version is running 6.1.2 by hitting the `/api/v2/about` endpoint

**Comment by niemyjski** [comment]
Doh, I'm not sure how this is running in my local setup as I'm not getting any errors but when I run it from docker compose single file I see it. It was due to the pr had the dns-prefix url wrong for the cdn and I didn't catch that and used that for the security headers and it worked in dev so I pushed a release. I'm double confirming it but doing a new minor right now.

**Comment by YanmaY** [comment]
Sorry for my mistake and it's OK now
Thank you👍

**Comment by XLJ-CN** [comment]
thank you,it works,I download the image of version 6.1.3,it works!
thank you very much

**Comment by 107295472** [comment]
cdn not available in china

**Comment by niemyjski** [comment]
@107295472 we'd be more than happy to accept a pr for bringing in the dependencies but at this time we can't keep changing the cdn every year when a global acceptable cdn gets banned.

**Comment by 107295472** [comment]
Can't you use a cdn?

**Comment by pccai** [comment]
cdn.jsdelivr.net doamin is 404！！！！

**Comment by niemyjski** [comment]
@pccai we'd be more than happy to accept a pr for bringing in the dependencies but at this time we can't keep changing the cdn every year when a global acceptable cdn gets banned.

**Comment by niemyjski** [comment]
There has been a lot of requests lately. Are there any acceptable cdns that will work in China that could be used or would anyone be willing to work on bundling the cdn deps into a vendor bundle (better). It should be easy work and we are all developers here.

**Comment by ejsmith** [comment]
Seems like there is quite a few requests for removing CDN because it doesn't work in China. The problem is that we want to use a CDN, but I don't know if there are any that work in China without us having to pay for one. As far as I know, we have zero paying customers from China. It would be really nice to get some help with this since we've spend 1000s of hours working on this app and made it open source and free to host on your own. If you find the project valuable, seems fair that you could try and help support it by contributing to it.

**Comment by 107295472** [comment]
Bundled into vendor bundle, tried and failed

**Comment by ejsmith** [comment]
Are you saying that you tried to fix it, but failed because you couldn't download the files?

**Comment by 107295472** [comment]
yes

**Comment by niemyjski** [comment]
@107295472 Did you try downloading them from a npm?

**Comment by 107295472** [comment]
You can definitely download it manually on npm, but you can't pull it down if you want to build the project and pull the components.
